<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Charity;
use Carbon\Carbon;

class CharitySeeder20Records extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $charities = [
            [
                'registration_number' => '888384062RR0001',
                'charity_name' => 'VICTORIA MILITARY MUSIC FESTIVAL SOCIETY',
                'charity_status' => 'Registered',
                'effective_date_of_status' => Carbon::createFromFormat('d/m/Y','08/06/1993'),
                'sanction' => null,
                'designation_code' => '1',
                'category_code' => '190',
                'address' => '132 WELLINGTON AVE',
                'city' => 'VICTORIA',
                'province' => 'BC',
                'country' => 'CA',
                'postal_code' => 'V8V4H7',
            ],
            [
                'registration_number' => '865861660RR0001',
                'charity_name' => 'VICTORIA MIRACLE CENTRE',
                'charity_status' => 'Registered',
                'effective_date_of_status' => Carbon::createFromFormat('d/m/Y','11/10/2002'),
                'sanction' => null,
                'designation_code' => '1',
                'category_code' => '70',
                'address' => '2985 ADMIRALS ROAD',
                'city' => 'VICTORIA',
                'province' => 'BC',
                'country' => 'CA',
                'postal_code' => 'V9A2R7',
            ], [
                'registration_number' => '108172933RR0001',
                'charity_name' => 'VICTORIA NATIVE FRIENDSHIP CENTRE',
                'charity_status' => 'Registered',
                'effective_date_of_status' => Carbon::createFromFormat('d/m/Y','25/03/1969'),
                'sanction' => null,
                'designation_code' => '1',
                'category_code' => '1',
                'address' => '231 REGINA AVE',
                'city' => 'VICTORIA',
                'province' => 'BC',
                'country' => 'CA',
                'postal_code' => 'V8Z1J6',
            ], [
                'registration_number' => '119284347RR0001',
                'charity_name' => 'VICTORIA NATURAL HISTORY SOCIETY',
                'charity_status' => 'Registered',
                'effective_date_of_status' => Carbon::createFromFormat('d/m/Y','16/05/1974'),
                'sanction' => null,
                'designation_code' => '1',
                'category_code' => '200',
                'address' => '3837 BLUE VALLEY RD',
                'city' => 'VICTORIA',
                'province' => 'BC',
                'country' => 'CA',
                'postal_code' => 'V9E1C8',
            ], [
                'registration_number' => '892201641RR0001',
                'charity_name' => 'VICTORIA NIKKEI CULTURAL SOCIETY',
                'charity_status' => 'Registered',
                'effective_date_of_status' => Carbon::createFromFormat('d/m/Y','29/05/1996'),
                'sanction' => null,
                'designation_code' => '1',
                'category_code' => '200',
                'address' => '3960 ASHFORD ROAD',
                'city' => 'VICTORIA',
                'province' => 'BC',
                'country' => 'CA',
                'postal_code' => 'V8P3S5',
            ], [
                'registration_number' => '119285039RR0001',
                'charity_name' => 'VICTORIA OPERATIC SOCIETY',
                'charity_status' => 'Registered',
                'effective_date_of_status' => Carbon::createFromFormat('d/m/Y','01/03/1975'),
                'sanction' => null,
                'designation_code' => '1',
                'category_code' => '190',
                'address' => '10-744 FAIRVIEW RD',
                'city' => 'VICTORIA',
                'province' => 'BC',
                'country' => 'CA',
                'postal_code' => 'V9A5T9',
            ], [
                'registration_number' => '890786742RR0001',
                'charity_name' => 'VICTORIA PALAEONTOLOGY SOCIETY',
                'charity_status' => 'Registered',
                'effective_date_of_status' => Carbon::createFromFormat('d/m/Y','01/01/1995'),
                'sanction' => null,
                'designation_code' => '1',
                'category_code' => '13',
                'address' => '1504 SHORNCLIFFE ROAD',
                'city' => 'VICTORIA',
                'province' => 'BC',
                'country' => 'CA',
                'postal_code' => 'V8P2T4',
            ], [
                'registration_number' => '817635949RR0001',
                'charity_name' => 'VICTORIA PHILHARMONIC CHOIR SOCIETY',
                'charity_status' => 'Registered',
                'effective_date_of_status' => Carbon::createFromFormat('d/m/Y','20/01/2006'),
                'sanction' => null,
                'designation_code' => '1',
                'category_code' => '12',
                'address' => 'BOX 38040,',
                'city' => 'VICTORIA',
                'province' => 'BC',
                'country' => 'CA',
                'postal_code' => 'V8W3N2',
            ], [
                'registration_number' => '868473422RR0001',
                'charity_name' => 'VICTORIA PROVIDENCE COMMUNITY CHURCH',
                'charity_status' => 'Registered',
                'effective_date_of_status' => Carbon::createFromFormat('d/m/Y','16/03/1999'),
                'sanction' => null,
                'designation_code' => '1',
                'category_code' => '30',
                'address' => 'P.O. BOX 42035',
                'city' => 'VICTORIA',
                'province' => 'BC',
                'country' => 'CA',
                'postal_code' => 'V8R6T4',
            ], [
                'registration_number' => '891430944RR0001',
                'charity_name' => 'VICTORIA REMEMBRANCE DAY COMMITTEE POPPY FUND',
                'charity_status' => 'Registered',
                'effective_date_of_status' => Carbon::createFromFormat('d/m/Y','01/10/1992'),
                'sanction' => null,
                'designation_code' => '1',
                'category_code' => '1',
                'address' => '411 GORGE RD EAST',
                'city' => 'VICTORIA',
                'province' => 'BC',
                'country' => 'CA',
                'postal_code' => 'V8T2W1',
            ], [
                'registration_number' => '890764947RR0001',
                'charity_name' => 'VICTORIA REVIVAL CENTRE',
                'charity_status' => 'Registered',
                'effective_date_of_status' => Carbon::createFromFormat('d/m/Y','20/01/1990'),
                'sanction' => null,
                'designation_code' => '1',
                'category_code' => '30',
                'address' => '5095 DEL MONTE AVENUE',
                'city' => 'VICTORIA',
                'province' => 'BC',
                'country' => 'CA',
                'postal_code' => 'V8Y1W9',
            ], [
                'registration_number' => '864450531RR0001',
                'charity_name' => 'VICTORIA REVIVAL FELLOWSHIP',
                'charity_status' => 'Registered',
                'effective_date_of_status' => Carbon::createFromFormat('d/m/Y','20/06/2002'),
                'sanction' => null,
                'designation_code' => '1',
                'category_code' => '70',
                'address' => '246 CADILLAC AVE',
                'city' => 'VICTORIA',
                'province' => 'BC',
                'country' => 'CA',
                'postal_code' => 'V8Z1T8',
            ], [
                'registration_number' => '107982472RR0001',
                'charity_name' => 'VICTORIA SINGLE PARENT RESOURCE CENTRE SOCIETY',
                'charity_status' => 'Registered',
                'effective_date_of_status' => Carbon::createFromFormat('d/m/Y','01/10/1978'),
                'sanction' => null,
                'designation_code' => '1',
                'category_code' => '1',
                'address' => '602 GORGE RD E',
                'city' => 'VICTORIA',
                'province' => 'BC',
                'country' => 'CA',
                'postal_code' => 'V8T2W6',
            ], [
                'registration_number' => '119285237RR0001',
                'charity_name' => 'VICTORIA SOCIETY FOR CHILDREN WITH AUTISM',
                'charity_status' => 'Registered',
                'effective_date_of_status' => Carbon::createFromFormat('d/m/Y','11/12/1977'),
                'sanction' => null,
                'designation_code' => '1',
                'category_code' => '100',
                'address' => '306 - 620 VIEW ST',
                'city' => 'VICTORIA',
                'province' => 'BC',
                'country' => 'CA',
                'postal_code' => 'V8W1J6',
            ], [
                'registration_number' => '888754744RR0001',
                'charity_name' => 'VICTORIA SOCIETY FOR HUMANISTIC JUDAISM',
                'charity_status' => 'Registered',
                'effective_date_of_status' => Carbon::createFromFormat('d/m/Y','24/04/1996'),
                'sanction' => null,
                'designation_code' => '1',
                'category_code' => '11',
                'address' => '3636 SHELBOURNE ST',
                'city' => 'VICTORIA',
                'province' => 'BC',
                'country' => 'CA',
                'postal_code' => 'V8P4H2',
            ], [
                'registration_number' => '890849748RR0001',
                'charity_name' => 'VICTORIA SUMMER MUSIC FESTIVAL SOCIETY',
                'charity_status' => 'Registered',
                'effective_date_of_status' => Carbon::createFromFormat('d/m/Y','28/05/1996'),
                'sanction' => null,
                'designation_code' => '1',
                'category_code' => '190',
                'address' => 'P.O. BOX 5203',
                'city' => 'VICTORIA',
                'province' => 'BC',
                'country' => 'CA',
                'postal_code' => 'V8R6N4',
            ], [
                'registration_number' => '119285286RR0001',
                'charity_name' => 'VICTORIA SYMPHONY SOCIETY',
                'charity_status' => 'Registered',
                'effective_date_of_status' => Carbon::createFromFormat('d/m/Y','01/06/1979'),
                'sanction' => null,
                'designation_code' => '1',
                'category_code' => '190',
                'address' => '610-620 VIEW ST',
                'city' => 'VICTORIA',
                'province' => 'BC',
                'country' => 'CA',
                'postal_code' => 'V8W1J6',
            ], [
                'registration_number' => '890886997RR0001',
                'charity_name' => 'VICTORIA TARGET THEATRE SOCIETY',
                'charity_status' => 'Registered',
                'effective_date_of_status' => Carbon::createFromFormat('d/m/Y','01/05/1991'),
                'sanction' => null,
                'designation_code' => '1',
                'category_code' => '190',
                'address' => 'P.O.BOX# 8421',
                'city' => 'VICTORIA',
                'province' => 'BC',
                'country' => 'CA',
                'postal_code' => 'V8W3S1',
            ], [
                'registration_number' => '119285302RR0001',
                'charity_name' => 'VICTORIA TRUTH CENTRE, INC',
                'charity_status' => 'Registered',
                'effective_date_of_status' => Carbon::createFromFormat('d/m/Y','01/01/1967'),
                'sanction' => null,
                'designation_code' => '1',
                'category_code' => '30',
                'address' => '2815 CEDAR HILL RD',
                'city' => 'VICTORIA',
                'province' => 'BC',
                'country' => 'CA',
                'postal_code' => 'V8T3H6',
            ],
        ];

        foreach ($charities as $charity) {
            Charity::updateOrCreate($charity);
        }
    }
}

