<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class EmployeeJobMissing extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $missed_jobs = [
            ['guid' => '2D4CE31B847B409E83AF6142530F220D',	'employee_id' => '068687',	'empl_record' => 0,	'employee_first_name' => 'Julie',	'employee_last_name' => 'Pinette',	'employee_status' => 'P',	'employee_email' => 'Julie.Pinette@gov.bc.ca',	'classification' => '',	'deptid' => '128-3155',	'jobcode' => '551505',	'job_title' => 'Administrative Officer R24',	'position_number' => '00124493',	'position_title' => '',	'position_start_date' => '2019-12-09',	'manager_id' => '',	'manager_first_name' => '',	'manager_last_name' => '',	'organization' => 'Forests',	'job_indicator' => 'P',	'tgb_reg_district' => '003',	'supervisor_position_title' => '',	'supervisor_position_start_date' => '',	'supervisor_emplid' => '',	'supervisor_position_number' => '00080330',	'supervisor_name' => '',	'supervisor_email' => '',	'stateprovince' => 'BC',	'sal_admin_plan' => 'GEU',	'public_service_act' => 'PS Act',	'postal' => 'V2G 3Y4   ',	'phone' => '250/398-6154',	'office_stateprovince' => 'BC',	'office_postal' => 'V8W 2H1',	'office_phone' => '',	'office_location_code' => 'V8W2H101',	'office_country' => 'CAN',	'office_city' => 'Victoria',	'office_address2' => ' ',	'office_address' => '4th floor 780 Blanshard',	'employee_name' => 'Pinette,Julie S',	'employee_middle_name' => 'S',	'level4' => '',	'level3_branch' => 'Lands',	'level2_division' => 'Lands Branch',	'level1_program' => 'Integrated Resource Operations',	'jobcode_desc' => 'Administrative Officer R24',	'job_function_employee_group' => 'BCGEU',	'employee_status_long' => 'Leave With Pay',	'country' => 'CAN',	'city' => 'Williams Lake                 ',	'can_noc_code' => '1221',	'appointment_status' => 'Regular',	'address2' => '',	'address1' => '740 4th Ave N',	'paygroup' => 'STD',	'occupationalgroup' => 'Corporate Roles',	'jobcodedescgroup' => 'Administrative Officer',	'job_function' => '111',	'idir' => 'jpinette',	'hire_dt' => '1993-03-01',	'empl_ctg' => 'R',	'empl_class' => 'B',	'effseq' => '0',	'effdt' => '2022-04-01',	'classification_group' => 'Senior Admin & Research',	'business_unit' => 'BC128',	'date_posted' => '', 'date_updated' => '2022-07-04 07:02:27',	'date_deleted' => ''],
            ['guid' => '3D5B839DC5D147FBA03FCCE853BEAF54',	'employee_id' => '145988',	'empl_record' => 0,	'employee_first_name' => 'Pamela',	'employee_last_name' => 'Goffic',	'employee_status' => 'A',	'employee_email' => 'Pamela.Goffic@gov.bc.ca',	'classification' => '',	'deptid' => '031-7254',	'jobcode' => '551505',	'job_title' => 'Administrative Officer R24',	'position_number' => '00120299',	'position_title' => '',	'position_start_date' => '2018-09-17',	'manager_id' => '',	'manager_first_name' => '',	'manager_last_name' => '',	'organization' => 'Social Development and Poverty Reduction',	'job_indicator' => 'P',	'tgb_reg_district' => '022',	'supervisor_position_title' => '',	'supervisor_position_start_date' => '',	'supervisor_emplid' => '',	'supervisor_position_number' => '00106545',	'supervisor_name' => '',	'supervisor_email' => '',	'stateprovince' => 'BC',	'sal_admin_plan' => 'GEU',	'public_service_act' => 'PS Act',	'postal' => 'V0V 1G0',	'phone' => '778/884-1240',	'office_stateprovince' => 'BC',	'office_postal' => 'V8J 3T1',	'office_phone' => '',	'office_location_code' => 'V8J3T102',	'office_country' => 'CAN',	'office_city' => 'Prince Rupert',	'office_address2' => ' ',	'office_address' => '#375 - 309 2nd Avenue West',	'employee_name' => 'Goffic,Pamela',	'employee_middle_name' => ' ',	'level4' => '054 Planning Innov & Performan',	'level3_branch' => 'PLANNING, INNOVATION AND PERFORMANCE',	'level2_division' => 'STRATEGIC SERVICES',	'level1_program' => 'Service Delivery Division',	'jobcode_desc' => 'Administrative Officer R24',	'job_function_employee_group' => 'BCGEU',	'employee_status_long' => 'Active',	'country' => 'CAN',	'city' => 'Port Edward',	'can_noc_code' => '1221',	'appointment_status' => 'Regular',	'address2' => '',	'address1' => '180 Hillcrest',	'paygroup' => 'STD',	'occupationalgroup' => 'Corporate Roles',	'jobcodedescgroup' => 'Administrative Officer',	'job_function' => '111',	'idir' => 'pagoffic',	'hire_dt' => '2011-03-14',	'empl_ctg' => 'R',	'empl_class' => 'B',	'effseq' => '0',	'effdt' => '2022-06-02',	'classification_group' => 'Senior Admin & Research',	'business_unit' => 'BC031',	'date_posted' => '', 'date_updated' => '2022-06-20 07:02:24',	'date_deleted' => ''],
            ['guid' => '4D2468C3BFEE433094DC3201482FE0C2',	'employee_id' => '160777',	'empl_record' => 0,	'employee_first_name' => 'Alyson',	'employee_last_name' => 'Rondeau',	'employee_status' => 'A',	'employee_email' => 'Alyson.Rondeau@gov.bc.ca',	'classification' => '',	'deptid' => '125-5544',	'jobcode' => '185002',	'job_title' => 'Band 2',	'position_number' => '00122837',	'position_title' => '',	'position_start_date' => '2021-04-26',	'manager_id' => '',	'manager_first_name' => '',	'manager_last_name' => '',	'organization' => 'Jobs, Economic Recovery and Innovation',	'job_indicator' => 'P',	'tgb_reg_district' => '027',	'supervisor_position_title' => '',	'supervisor_position_start_date' => '',	'supervisor_emplid' => '162377',	'supervisor_position_number' => '00116850',	'supervisor_name' => 'Evans,Erin',	'supervisor_email' => 'Erin.Evans@gov.bc.ca',	'stateprovince' => 'BC',	'sal_admin_plan' => 'MGT',	'public_service_act' => 'PS Act',	'postal' => 'V5Z 1B6',	'phone' => '604/417-6835',	'office_stateprovince' => 'BC',	'office_postal' => 'V8W 9N3',	'office_phone' => '',	'office_location_code' => 'V8W9N300',	'office_country' => 'CAN',	'office_city' => 'Victoria',	'office_address2' => '5th  Floor - 800 Johnson Street',	'office_address' => 'PO Box 9800 STN PROV GOVT',	'employee_name' => 'Rondeau,Alyson Ashley Mei',	'employee_middle_name' => 'Ashley Mei',	'level4' => 'Inn,Strat,Policy & Coordinatio',	'level3_branch' => 'Planning and Innovation',	'level2_division' => 'Innovation Tech & Invest Capital',	'level1_program' => 'Investment, Innovation and Technology Division',	'jobcode_desc' => 'Band 2',	'job_function_employee_group' => 'Management',	'employee_status_long' => 'Active',	'country' => 'CAN',	'city' => 'Vancouver',	'can_noc_code' => '4168',	'appointment_status' => 'Regular',	'address2' => '',	'address1' => '207-685 West 7th Ave',	'paygroup' => 'STD',	'occupationalgroup' => 'Management',	'jobcodedescgroup' => 'Band 2',	'job_function' => '047',	'idir' => 'alrondea',	'hire_dt' => '2016-08-25',	'empl_ctg' => 'R',	'empl_class' => 'M',	'effseq' => '1',	'effdt' => '2021-10-08',	'classification_group' => 'Management Band',	'business_unit' => 'BC125',		'date_posted' => '', 'date_updated' => '2022-06-20 07:02:24',	'date_deleted' => ''],
            ['guid' => '7C8E24396B6D4BE29E4E29CE627D3101',	'employee_id' => '124905',	'empl_record' => 0,	'employee_first_name' => 'Jennifer', 'employee_last_name' => 'Helmy',	'employee_status' => 'A',	'employee_email' => 'Jennifer.Fox@gov.bc.ca',	'classification' => '',	'deptid' => '010-4101',	'jobcode' => '185004',	'job_title' => 'Band 4',	'position_number' => '00016040',	'position_title' => '',	'position_start_date' => '2021-01-04',	'manager_id' => '',	'manager_first_name' => '',	'manager_last_name' => '',	'organization' => 'Justice',	'job_indicator' => 'P',	'tgb_reg_district' => '028',	'supervisor_position_title' => '',	'supervisor_position_start_date' => '',	'supervisor_emplid' => '100691',	'supervisor_position_number' => '00117270',	'supervisor_name' => 'Lennox,Brenda G.',	'supervisor_email' => 'Brenda.Lennox@gov.bc.ca',	'stateprovince' => 'BC',	'sal_admin_plan' => 'MGT',	'public_service_act' => 'PS Act',	'postal' => 'V9C 0M6',	'phone' => '250/891-3388',	'office_stateprovince' => 'BC',	'office_postal' => 'V9A 6X5',	'office_phone' => '',	'office_location_code' => 'V9A6X502',	'office_country' => 'CAN',	'office_city' => 'Victoria',	'office_address2' => ' ',	'office_address' => '3rd Floor 645 TYEE RD',	'employee_name' => 'Helmy,Jennifer',	'employee_middle_name' => ' ',	'level4' => 'CS - LCRB',	'level3_branch' => 'Management Services - LCRB',	'level2_division' => 'Corporate and Strategic Services Division',	'level1_program' => 'Liquor & Cannabis Regulation Branch',	'jobcode_desc' => 'Band 4',	'job_function_employee_group' => 'Management',	'employee_status_long' => 'Active',	'country' => 'CAN',	'city' => 'Victoria',	'can_noc_code' => '0414',	'appointment_status' => 'Regular',	'address2' => '',	'address1' => '1106 Crispin Place',	'paygroup' => 'STD',	'occupationalgroup' => 'Management',	'jobcodedescgroup' => 'Band 4',	'job_function' => '047',	'idir' => 'jfox',	'hire_dt' => '2004-07-12',	'empl_ctg' => 'R',	'empl_class' => 'M',	'effseq' => '0',	'effdt' => '2021-07-19',	'classification_group' => 'Management Band',	'business_unit' => 'BC010',		'date_posted' => '', 'date_updated' => '2022-08-15 07:03:20',	'date_deleted' => '2022-08-22 07:02:45'],
            ['guid' => 'B3145A4D96F04023A9F1B78572048AD4',	'employee_id' => '056353',	'empl_record' => 0,	'employee_first_name' => 'Norma',	'employee_last_name' => 'Ritchie',	'employee_status' => 'P',	'employee_email' => 'Norma.Ritchie@gov.bc.ca',	'classification' => '',	'deptid' => '062-2035',	'jobcode' => '551104',	'job_title' => 'Clerk R11',	'position_number' => '00033905',	'position_title' => '',	'position_start_date' => '2004-01-26',	'manager_id' => '',	'manager_first_name' => '',	'manager_last_name' => '',	'organization' => 'Education and Child Care',	'job_indicator' => 'P',	'tgb_reg_district' => '028',	'supervisor_position_title' => '',	'supervisor_position_start_date' => '',	'supervisor_emplid' => '056288',	'supervisor_position_number' => '00081543',	'supervisor_name' => 'Sehmi,Havind',	'supervisor_email' => 'Havind.Sehmi@gov.bc.ca',	'stateprovince' => 'BC',	'sal_admin_plan' => 'GEU',	'public_service_act' => 'PS Act',	'postal' => 'V8P 4B2   ',	'phone' => '250/592-5059',	'office_stateprovince' => 'BC',	'office_postal' => 'V8V 1V2',	'office_phone' => '',	'office_location_code' => 'V8V1V204',	'office_country' => 'CAN',	'office_city' => 'Victoria',	'office_address2' => ' ',	'office_address' => '4 - 620 Superior St.',	'employee_name' => 'Ritchie,Norma J',	'employee_middle_name' => 'J',	'level4' => '',	'level3_branch' => '',	'level2_division' => '',	'level1_program' => 'Learning Division',	'jobcode_desc' => 'Clerk R11',	'job_function_employee_group' => 'BCGEU',	'employee_status_long' => 'Leave With Pay',	'country' => 'CAN',	'city' => 'Victoria                      ',	'can_noc_code' => '1411',	'appointment_status' => 'Regular',	'address2' => '',	'address1' => '3319 Keats St',	'paygroup' => 'STD',	'occupationalgroup' => 'Clerical',	'jobcodedescgroup' => 'Clerk',	'job_function' => '111',	'idir' => 'njritchi',	'hire_dt' => '1992-04-21',	'empl_ctg' => 'R',	'empl_class' => 'B',	'effseq' => '0',	'effdt' => '2022-08-06',	'classification_group' => 'Admin Support',	'business_unit' => 'BC062', 	'date_posted' => '', 'date_updated' => '2022-08-15 07:03:20',	'date_deleted' => ''],
            ['guid' => 'C6E200F19D0B4636BC67A566754FD3B4',	'employee_id' => '126435',	'empl_record' => 0,	'employee_first_name' => 'Robert',	'employee_last_name' => 'Rail',	    'employee_status' => 'P',	'employee_email' => 'Rob.Rail@gov.bc.ca',	    'classification' => '',	'deptid' => '039-2316',	'jobcode' => '185004',	'job_title' => 'Band 4',	'position_number' => '00101053',	'position_title' => '',	'position_start_date' => '2010-08-03',	'manager_id' => '',	'manager_first_name' => '',	'manager_last_name' => '',	'organization' => 'Children and Family Development',	'job_indicator' => 'P',	'tgb_reg_district' => '013',	'supervisor_position_title' => '',	'supervisor_position_start_date' => '',	'supervisor_emplid' => '120065',	'supervisor_position_number' => '00113823',	'supervisor_name' => 'Lee,Jackie Susanne',	'supervisor_email' => 'Jackie.Lee@gov.bc.ca',	'stateprovince' => 'BC',	'sal_admin_plan' => 'MGT',	'public_service_act' => 'PS Act',	'postal' => 'V2M1L6',	'phone' => '250 6494240',	'office_stateprovince' => 'BC',	'office_postal' => 'V2L 3H9',	'office_phone' => '',	'office_location_code' => 'V2L3H907',	'office_country' => 'CAN',	'office_city' => 'Prince George',	'office_address2' => ' ',	'office_address' => '#462 1011 4th Avenue',	'employee_name' => 'Rail,Robert Donald',	'employee_middle_name' => 'Donald',	'level4' => '',	'level3_branch' => 'XMS-Quality Assurance Practice',	'level2_division' => 'Quality Assurance',	'level1_program' => 'Provincial  Dir of Child Welfare & Aboriginal Services',	'jobcode_desc' => 'Band 4',	'job_function_employee_group' => 'Management',	'employee_status_long' => 'Leave With Pay',	'country' => 'CAN',	'city' => 'Prince George',	'can_noc_code' => '0411',	'appointment_status' => 'Regular',	'address2' => '',	'address1' => '1840 - 6th Avenue',	'paygroup' => 'STD',	'occupationalgroup' => 'Management',	'jobcodedescgroup' => 'Band 4',	'job_function' => '047',	'idir' => 'rdrail',	'hire_dt' => '2005-04-25',	'empl_ctg' => 'R',	'empl_class' => 'M',	'effseq' => '0',	'effdt' => '2022-07-05',	'classification_group' => 'Management Band',	'business_unit' => 'BC039',		'date_posted' => '', 'date_updated' => '2022-07-18 07:02:31',	'date_deleted' => ''],
            ['guid' => 'D67587F9A1C947EEACE8A93E6640FB23',	'employee_id' => '175887',	'empl_record' => 0,	'employee_first_name' => 'Shruthi',	'employee_last_name' => 'Sridhar',	'employee_status' => 'A',	'employee_email' => 'shruthi.sridhar@pensionsbc.ca',	'classification' => '',	'deptid' => '088-6220',	'jobcode' => '508009',	'job_title' => 'Information Systems R21',	'position_number' => '00117990',	'position_title' => '',	'position_start_date' => '2021-01-04',	'manager_id' => '',	'manager_first_name' => '',	'manager_last_name' => '',	'organization' => 'BC Pension Corp',	'job_indicator' => 'P',	'tgb_reg_district' => '028',	'supervisor_position_title' => '',	'supervisor_position_start_date' => '',	'supervisor_emplid' => '171631',	'supervisor_position_number' => '00132986',	'supervisor_name' => 'Ozbilim,Gozde',	'supervisor_email' => 'gozde.ozbilim@pensionsbc.ca',	'stateprovince' => 'BC',	'sal_admin_plan' => 'GEU',	'public_service_act' => 'PS Act',	'postal' => 'V8W 2K5',	'phone' => '647/580-8507',	'office_stateprovince' => 'BC',	'office_postal' => 'V8W 9V8',	'office_phone' => '',	'office_location_code' => 'V8W9V800',	'office_country' => 'CAN',	'office_city' => 'Victoria',	'office_address2' => ' ',	'office_address' => '2995 Jutland Rd',	'employee_name' => 'Sridhar,Shruthi',	'employee_middle_name' => ' ',	'level4' => '',	'level3_branch' => 'ITS-Bus Services Portfolio 1',	'level2_division' => 'Business Services',	'level1_program' => 'Information Technology Services',	'jobcode_desc' => 'Information Systems R21',	'job_function_employee_group' => 'BCGEU',	'employee_status_long' => 'Active',	'country' => 'CAN',	'city' => 'Victoria',	'can_noc_code' => '2171',	'appointment_status' => 'Regular',	'address2' => '',	'address1' => '1406-1147 Quadra Street',	'paygroup' => 'STD',	'occupationalgroup' => 'Corporate Roles',	'jobcodedescgroup' => 'Information Systems',	'job_function' => '118',	'idir' => 'shrsridh',	'hire_dt' => '2020-02-10',	'empl_ctg' => 'R',	'empl_class' => 'B',	'effseq' => '0',	'effdt' => '2022-07-26',	'classification_group' => 'Information Technology',	'business_unit' => 'BC088',	'date_posted' => '', 'date_updated' => '2022-08-01 07:02:24',	'date_deleted' => '2022-08-22 07:02:45'],
            ['guid' => 'F93D7FCFE3CC4462BACA72C27419629A',	'employee_id' => '108797',	'empl_record' => 0,	'employee_first_name' => 'Julia',	'employee_last_name' => 'Muldoe',	'employee_status' => 'A',	'employee_email' => 'Julia.Muldoe@gov.bc.ca',	'classification' => '',	'deptid' => '039-2339',	'jobcode' => '501177',	'job_title' => 'Social Prog Off R30',	'position_number' => '00109500',	'position_title' => '',	'position_start_date' => '2021-03-29',	'manager_id' => '',	'manager_first_name' => '',	'manager_last_name' => '',	'organization' => 'Children and Family Development',	'job_indicator' => 'P',	'tgb_reg_district' => '014',	'supervisor_position_title' => '',	'supervisor_position_start_date' => '',	'supervisor_emplid' => '157683',	'supervisor_position_number' => '00056356',	'supervisor_name' => 'Maillet,Jennifer L',	'supervisor_email' => 'Jennifer.Maillet@gov.bc.ca',	'stateprovince' => 'BC',	'sal_admin_plan' => 'GEU',	'public_service_act' => 'PS Act',	'postal' => 'V0J 1Y1',	'phone' => '250/877-8958',	'office_stateprovince' => 'BC',	'office_postal' => 'V0J 1Y0',	'office_phone' => '',	'office_location_code' => 'V0J1Y000',	'office_country' => 'CAN',	'office_city' => 'Hazelton',	'office_address2' => 'Box 215',	'office_address' => '2210 West Highway 62',	'employee_name' => 'Muldoe,Julia Ruthana-Louise',	'employee_middle_name' => 'Ruthana-Louise',	'level4' => 'QMF-Youth Justice',	'level3_branch' => 'LSA - Stikine , NW YJ & CYMH',	'level2_division' => 'SDA 41 - Northwest',	'level1_program' => 'Service Delivery',	'jobcode_desc' => 'Social Prog Off R30',	'job_function_employee_group' => 'BCGEU',	'employee_status_long' => 'Active',	'country' => 'CAN',	'city' => 'Hazelton',	'can_noc_code' => '4152',	'appointment_status' => 'Regular',	'address2' => '',	'address1' => '4820 Strathern Rd.',	'paygroup' => 'STD',	'occupationalgroup' => 'Social & Related Front-Line Positions',	'jobcodedescgroup' => 'Social Program Officer',	'job_function' => '118',	'idir' => 'jrmuldoe',	'hire_dt' => '1999-02-08',	'empl_ctg' => 'R',	'empl_class' => 'B',	'effseq' => '0',	'effdt' => '2021-04-11',	'classification_group' => 'Health, Education & Social Work',	'business_unit' => 'BC039', 'date_posted' => '', 'date_updated' => '2022-08-01 07:02:24',	'date_deleted' => ''],
            // From spreadsheet
            ['guid' => 'EDE4706EA898446CA92684C458A0743F',	'employee_id' => '119765',	'empl_record' => 0, 'employee_first_name' => 'Carol',	'employee_last_name' => 'Whittome',	'employee_status' => 'T',	'employee_email' => 'Carol.Whittome@bcfsa.ca',	'classification' => '',	'deptid' => '022-2645',	'jobcode' => '185003',	'job_title' => 'Policy and Legislative Analyst',	'position_number' => '113423',	'position_title' => '',		'position_start_date' => '2019-06-03',	'manager_id' => '',	'manager_first_name' => '',	'manager_last_name' => '',			'organization' => 'Finance',	'job_indicator' => 'P',	'tgb_reg_district' => '028', 'supervisor_position_title' => '',	'supervisor_position_start_date' => '', 'supervisor_emplid' => '153468',	'supervisor_position_number' => '00080330',	'supervisor_name' => 'Norman,Tiffany',	'supervisor_email' => 'Tiffany.Norman@gov.bc.ca',	'stateprovince' => 'BC',	'sal_admin_plan' => 'MGT',	'public_service_act' => 'PS Act',	'postal' => 'V8L 5G3',	'phone' => '250/886-6667',	'office_stateprovince' => 'BC',	'office_postal' => 'V8W 9V1',	'office_phone' => '',	'office_location_code' => 'V8V9V101',	'office_country' => 'CAN',	'office_city' => 'Victoria',	'office_address2' => ' ',	'office_address' => '2020-1810 Blanshard Street',	'employee_name' => 'Whittome,Carol L',	'employee_middle_name' => 'L',	'level4' => 'PLD Fin & Corp Sector Policy',	'level3_branch' => 'Finance & Corporate Sector Policy',	'level2_division' => 'Finance Real Estate & Data Analytics and Finance & Corporate Sector Policy',	'level1_program' => 'Policy & Legislation Division',	'jobcode_desc' => 'Administrative Officer R24',	'job_function_employee_group' => 'Management',	'employee_status_long' => 'Terminated',	'country' => 'CAN',	'city' => 'North Saanich',	'can_noc_code' => '412',	'appointment_status' => 'Regular',	'address2' => ' ',	'address1' => '642 Aboyne Ave',	'paygroup' => 'STD',	'occupationalgroup' => 'Management',	'jobcodedescgroup' => 'Band 3',	'job_function' => '47',	'idir' => 'cawhitto',	'hire_dt' => '2002-05-06',	'empl_ctg' => 'R',	'empl_class' => 'M',	'effseq' => '0',	'effdt' => '2022-12-10',	'classification_group' => 'Management Band',	'business_unit' => 'BC022',	'created_at' => '',	'date_updated' => '2022-07-04 07:02:27', 	'date_deleted' => ''],
        ];

        $organization = \App\Models\Organization::where('code', 'GOV')->first();
        $business_units = \App\Models\BusinessUnit::pluck('id','code')->toArray();
        $regions = \App\Models\Region::pluck('id','code')->toArray();

        foreach ($missed_jobs as $row) {

             // $regional_district = RegionalDistrict::where('tgb_reg_district', $row['tgb_reg_district)->first();


            \App\Models\EmployeeJob::updateOrCreate([
                'guid' => $row['guid'],
            ], [
                'emplid' => $row['employee_id'],
                'empl_rcd' => $row['empl_record'],
                'organization_id' => $organization ? $organization->id : null,
                'effdt' => $row['effdt'],
                'effseq' => $row['effseq'],
                'empl_status' => $row['employee_status'],
                'empl_ctg' => $row['empl_ctg'],
                'empl_class' => $row['empl_class'],
                'job_indicator' => $row['job_indicator'],
                'position_number' => $row['position_number'],
                'position_title' => $row['position_title'],
                'appointment_status' => $row['appointment_status'],
                'first_name' => $row['employee_first_name'],
                'last_name' => $row['employee_last_name'],
                'name' => $row['employee_name'],
                'email' => $row['employee_email'],
                'guid' => trim($row['guid']),
                'idir' => trim($row['idir']),

                'business_unit' => $row['business_unit'],
                'business_unit_id' => array_key_exists( $row['business_unit'], $business_units) ? $business_units[$row['business_unit']] : null,
                'deptid' => $row['deptid'],
                'dept_name' => '',
                'tgb_reg_district' => $row['tgb_reg_district'],
                'region_id' => array_key_exists( $row['tgb_reg_district'] , $regions) ? $regions[$row['tgb_reg_district']] : null,

                'office_address1' => $row['office_address'],
                'office_address2' => $row['office_address2'],
                'office_city' => $row['office_city'], 
                'office_stateprovince' => $row['office_stateprovince'], 
                'office_country' => $row['office_country'],
                'office_postal' => $row['office_postal'],

                'city' => $row['city'],
                'stateprovince' => $row['stateprovince'],
                'country' => $row['country'],

                'organization' => trim($row['organization']),
                'level1_program' => trim($row['level1_program']),
                'level2_division' => trim($row['level2_division']),
                'level3_branch' => trim($row['level3_branch']),
                'level4' => trim($row['level4']),
                'supervisor_emplid' => $row['supervisor_emplid'],
                'supervisor_name' => $row['supervisor_name'],
                'supervisor_email' => $row['supervisor_email'],
                'date_updated' => $row['date_updated'] ? (substr($row['date_updated'],0,10).' '.substr($row['date_updated'],11,8)) : null,
                'date_deleted' => $row['date_deleted'] ? (substr($row['date_deleted'],0,10).' '.substr($row['date_deleted'],11,8)) : null,

                'created_by_id' => null,
                'updated_by_id' => null,

            ]);

        }


    }
}
