---
apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: "${APP_NAME}-${INSTANCE}"
  name: "${NAME}-${INSTANCE}"
  role: "${ROLE}"
  template: "pecsf-secrets-template"
metadata:
  annotations:
    description: MYSQL server secret generator.
    tags: "${NAME}-${INSTANCE}"
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: "${NAME}-${INSTANCE}-secret"
    stringData:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_ROOT_USER: "${MYSQL_ROOT_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      
    type: Opaque
parameters:
  - name: NAME
    displayName: Name
    description:
      The name assigned to all of the OpenShift resources associated to the
      server instance.
    required: true
    value: mysql
  - name: INSTANCE
    description: The name of this instance of the application
    displayName: Application Instance Name
    required: true
    value: prod
  - name: APP_NAME
    displayName: App Name
    description: Used to group components together in the OpenShift console.
    required: true
    value: mysql
  - name: ROLE
    displayName: Role
    description:
      The role of this service within the application - used for Network
      Policies
    required: true
    value: db
  - name: MYSQL_USER
    displayName: MYSQL Connection Username
    description:
      Username for MYSQL user that will be used for accessing the database.
    required: true
    value: pecsf
  - name: MYSQL_PASSWORD
    displayName: MYSQL Connection Password
    description: Password for the MYSQL connection user.
    required: true
    generate: expression
    from: "[a-zA-Z0-9]{32}"
  - name: MYSQL_ROOT_PASSWORD
    displayName: MYSQL Master Password
    description:
      Password for the MYSQL administrative account.
    required: true
    generate: expression
    from: "[a-zA-Z0-9]{32}"
  - name: MYSQL_ROOT_USER
    displayName: MYSQL Connection Username
    description:
      Username for MYSQL user that will be used for accessing the database.
    required: true
    value: root
  - name: MYSQL_DATABASE
    displayName: MYSQL Database name
    description:
      Database name
    required: true
    value: pecsf