apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config-map
data:
  primary.conf: |
    bind 0.0.0.0
    protected-mode no
    port 6379
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300
    daemonize no
    supervised no
    pidfile /var/run/redis_6379.pid
    loglevel notice
    logfile ""
    # requirepass ${REDIS_PASSWORD}
  secondary.conf: |
    slaveof redis-0.redis 6379
